### ISSUE TITLE
qemu-output not logging any CORB data

### ISSUE THREAD

**Issue by minhld139** [jeffsauer/lggram2023speakerfix#1]
Hi, I'm trying to do the same with LG Gram 16 2023, been able to follow throgh the end until ouput to `qemu-output.txt` file but it look like non of CORB data had been logged into the file, just only vfio_region_read like this below.
Do you have any suggestions?
Thanks!

`vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x58, 2) = 0xa3
vfio_region_read  (0000:00:1f.3:region0+0x20, 4) = 0x40000000
vfio_region_write  (0000:00:1f.3:region0+0x20, 0xc0000000, 4)`

**Comment by jeffsauer** [comment]
are you sure you compiled QEMU from source and added the patch as per step 1?  What version did you use?  Normally, missing CORB data means that the QEMU hasn't been patched with the CORB diagnostics added....

**Comment by minhld139** [comment]
Sorry, definitely my mistake here. I was call system-wide qemu instead of built from source. Fix the startwin11.sh file and now it work properly.
Thanks for your time
